name: Deploy
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Copy contents to server and create react build
              uses: appleboy/ssh-action@master
              with:
                  host: andres.run
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      cd /var/www
                      rm -rf bookmarks
                      git clone git@github.com:andresmarpz/bookmarks.git
                      cd bookmarks && npm install
                      touch .env
                      echo REACT_APP_CLIENT_ID=${{secrets.CLIENT_ID}} >> .env
                      npm run build
